DROP TABLE IF EXISTS discounts CASCADE;
DROP TABLE IF EXISTS platforms CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS station CASCADE;
DROP TABLE IF EXISTS carrier CASCADE;
DROP TABLE IF EXISTS trip CASCADE;
DROP TABLE IF EXISTS trip_interval CASCADE;
DROP TABLE IF EXISTS seat CASCADE;
DROP TABLE IF EXISTS line CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS ticket CASCADE;
DROP TABLE IF EXISTS trains CASCADE ;
DROP FUNCTION IF EXISTS calculate_price(int, int, varchar, int, int);
DROP FUNCTION IF EXISTS check_all();
DROP FUNCTION IF EXISTS after_delete_station();
DROP FUNCTION IF EXISTS after_delete_trip();
DROP FUNCTION IF EXISTS before_insert_trip();
DROP FUNCTION IF EXISTS tracks_on_station(int);
DROP FUNCTION IF EXISTS which_car(int, int);
DROP FUNCTION IF EXISTS first_free_track(int, interval);
DROP FUNCTION IF EXISTS give_track();
DROP FUNCTION IF EXISTS basic_price(int, int, int);
DROP FUNCTION IF EXISTS timetable(timestamp, varchar,varchar);
DROP FUNCTION IF EXISTS find_line(timestamp, varchar,varchar);